<a href="https://colab.research.google.com/github/LuchithaP/Deep-Learning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Outline


*   Introdution to tensors

*   getting information from tensors

*   manipulating tensors
*   Tensors and Numpy


*   using @tf.function ( a way to speed up regular python functions )


*  Using GPUs WITH tENSORFlow (or TPU)


*   Exercises






# Introduction

In [9]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.17.1


In [10]:
#create a tensor with tf.contant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [11]:
#check the num of dimensions in a tensor
scalar.ndim

0

In [14]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [13]:
vector.ndim

1

In [15]:
matrix  = tf.constant(
    [
        [10,7],
        [7,10]
    ]
)

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [16]:
matrix.ndim

2

In [23]:
another_matrix = tf.constant(
    [
        [1.,2.,3.],
        [4.,5.,6.],
        [7.,8.,9.]
    ]
    ,
    dtype = tf.float16
)
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float16)>

In [24]:
another_matrix.ndim


2

In [25]:
#create a tensor
tensor = tf.constant(
    [
        [
            [1,2,3], [3,2,5]
        ],
        [
            [4,5,6], [7,8,9]
        ],
        [
            [6,3,0],[8,9,-1]
        ]
    ]
)
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 3,  2,  5]],

       [[ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 6,  3,  0],
        [ 8,  9, -1]]], dtype=int32)>

In [26]:
tensor.ndim

3

# tf Variable

In [31]:
unchangeable_tensor = tf.constant([10,7])
changeble_tensor = tf.Variable([10,7])
unchangeable_tensor , changeble_tensor


(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [28]:
changeble_tensor[0].assign(7)
changeble_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

# Random Tensors

In [37]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.uniform(shape=(3,2) , maxval = 10 , minval = 5)  # take random values from a normal distribution
random_2 = tf.random.Generator.from_seed(40)
random_2 = random_2.normal(shape=(3,2))
random_1 , random_2 , random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[8.746723 , 8.678099 ],
        [7.2615395, 7.451991 ],
        [5.9446583, 7.601376 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.78953624,  0.53897345],
        [-0.48535708,  0.74055266],
        [ 0.31662667, -1.4391748 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [40]:
#shuffle the order of a tensor

not_shuffled = tf.constant(
    [
        [3,8,9],
        [9,1,5],
        [6,0,1]
    ]
)
shuffled = tf.random.shuffle(not_shuffled)

not_shuffled , shuffled


(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[3, 8, 9],
        [9, 1, 5],
        [6, 0, 1]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[9, 1, 5],
        [6, 0, 1],
        [3, 8, 9]], dtype=int32)>)


*   Global Seed Only: The shuffle result remains consistent across runs when the global seed is set.

*   Operation Seed Only: The shuffle result is consistent across runs for the specific operation with the given seed.

*   Both Seeds: The shuffle result is consistent across runs, but it will differ from the other cases as it depends on the combination of global and operation seeds.









In [123]:
tf.random.set_seed(12) #
shuffled = tf.random.shuffle(not_shuffled, seed = 42)
shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[9, 1, 5],
       [3, 8, 9],
       [6, 0, 1]], dtype=int32)>

In [126]:
#tf.ones
ones = tf.ones(shape = (5,3), dtype=tf.int32)
print(ones)
#tf.zeros
zeros = tf.zeros(shape = (4,3), dtype=tf.float16)
print(zeros)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]], shape=(5, 3), dtype=int32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(4, 3), dtype=float16)


#Numpy arrays to tensors

tensors run faster in GPUs than a Numpy array

In [130]:
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [132]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [135]:
B = tf.constant(numpy_A , shape = (2,3,4))
C  = tf.constant(numpy_A , shape = (3,8))
B , C

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)